[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0007"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0010"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\b"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0014"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000E"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000F"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = '\u00141'
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00142"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00143"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00144"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00145"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00146"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00147"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00148"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00149"
key = "Key9"
mods = "Command"

[terminal]

# Migration of the config was no longer using aliases
# TODO: figure out if I still want to use these (and what that like in TOML)
# [chars]
# ctl_b = "\u0002"
# ctl_g = "\u0007"
# ctl_h = "\b"
# ctl_n = "\u000E"
# ctl_o = "\u000F"
# ctl_p = "\u0010"
# ctl_r = "\u0012"
# ctl_s = "\u0013"
# ctl_t = "\u0014"
# ctl_t1 = "\u00141"
# ctl_t2 = "\u00142"
# ctl_t3 = "\u00143"
# ctl_t4 = "\u00144"
# ctl_t5 = "\u00145"
# ctl_t6 = "\u00146"
# ctl_t7 = "\u00147"
# ctl_t8 = "\u00148"
# ctl_t9 = "\u00149"

[colors.bright]
black = "0x4d4d4d"
blue = "0xcaa9fa"
cyan = "0xaa91e3"
green = "0x5af78e"
magenta = "0xff92d0"
red = "0xff6e67"
white = "0xe6e6e6"
yellow = "0xeaf08d"

[colors.cursor]
cursor = "0xf8f8f2"
text = "0x191622"

[colors.dim]
black = "0x000000"
blue = "0x530aba"
cyan = "0x433364"
green = "0x049f2b"
magenta = "0xbb006b"
red = "0xa90000"
white = "0x5f5f5f"
yellow = "0xa3b106"

[colors.normal]
black = "0x000000"
blue = "0xbd93f9"
cyan = "0x8d79ba"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbfbfbf"
yellow = "0xeffa78"

[colors.primary]
background = "0x191622"
foreground = "0xe1e1e6"

[font]
size = 18.0

[font.normal]
family = "MesloLGS Nerd Font Mono"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Command"

[terminal.shell]
program = "zsh"

[window]
option_as_alt = "Both"

[keyboard]
